site_name: BioLockJ User Guide
site_url: https://ivoryc.github.io/BioLockJ/
repo_url: https://github.com/BioLockJ-Dev-Team/BioLockJ
repo_name: BioLockJ
site_author: Ivory Blakley
copyright: 2019 Fodor Lab
plugins:
    - search
    - pdf-export:
        verbose: True
        combined: True
theme:
  name: 'material'
  custom_dir: 'customize_material_theme'
nav:
    - Home: index.md
    - Installation: Installation.md
    - Getting Started: Getting-Started.md
    - Commands: Commands.md
    - Configuration: Configuration.md
    - Example Pipeline: Example-Pipeline.md
    - Failure Recovery: Failure-Recovery.md
    - Building Modules: Building-Modules.md
    - Dependencies: Dependencies.md
    - FAQ: FAQ.md
    - Pipeline Componenets:
        Metadata: The-Metadata-File.md
    - Features:
        Validation: Validation.md
    - Modules:
        - classifiers:
            about classifiers: module.classifier.md
            module.classifier.r16s: module.classifier.r16s.md
            module.classifier.wgs: module.classifier.wgs.
        - implicit modules: 
            about implicit modules: module.implicit.md
            implicit parsers: module.implicit.parser.md
            module.implicit.parser.r16s.md: module.implicit.parser.r16s.md
            module.implicit.parser.wgs.md: module.implicit.parser.wgs.md
            implicit qiime modules: module.implicit.qiime.md
        - report modules:
            about report modules: module.report.md
            humann2: module.report.humann2.md
            report by otu: module.report.otu.md
            report by tax: module.report.taxa.md
            R reports: module.report.r.md
        - sequence modules: module.seq.md
        - DIY modules:
            GenMod: module.diy.md
