site_name: BioLockJ User Guide
docs_dir: docs
#site_url: https://ivoryc.github.io/BioLockJ
#repo_url: https://github.com/BioLockJ-Dev-Team/BioLockJ
repo_name: BioLockJ
site_author: Ivory Blakley
copyright: 2019 Fodor Lab

plugins:
    - search
#    - pdf-export:
#        verbose: True
#        combined: True
#        enabled_if_env: ENABLE_PDF_EXPORT
#        combined_output_path: BioLockJ_User_Guide.pdf

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme:
  name: 'readthedocs'
#  name: 'material'
#  custom_dir: 'customize_material_theme'
nav:
    - Home: index.md
    - Getting Started: Getting-Started.md
    - Commands: Commands.md
    - Pipeline Componenets:
        - Configuration: Configuration.md
        - Modules: Built-in-modules.md
        - Metadata: The-Metadata-File.md
        - Dependencies: Dependencies.md
    - Features:
        - Check Dependencies: Check-Dependencies.md
        - Failure Recovery: Failure-Recovery.md
        - Validation: Validation.md
        - Building Modules: Building-Modules.md
    - Example Pipeline: Example-Pipeline.md
    - FAQ: FAQ.md
    # - more:
    #     - module/classifier/module.classifier.md
    #     - module/classifier/module.classifier.r16s.md
    #     - module/classifier/module.classifier.wgs.md
    #     - module/diy/module.diy.md
    #     - module/implicit/module.implicit.md
    #     - module/implicit/module.implicit.parser.md
    #     - module/implicit/module.implicit.parser.r16s.md
    #     - module/implicit/module.implicit.parser.wgs.md
    #     - module/implicit/module.implicit.qiime.md
    #     - module/report/module.report.humann2.md
    #     - module/report/module.report.md
    #     - module/report/module.report.otu.md
    #     - module/report/module.report.r.md
    #     - module/report/module.report.taxa.md
    #     - module/seq/module.seq.md

    
